// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Core.Document.Avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class MetaData : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"MetaData\",\"namespace\":\"Core.Document.Avro\",\"fields\":[{\"n" +
				"ame\":\"version\",\"doc\":\"version of the uploaded document\",\"type\":\"string\"},{\"name\"" +
				":\"user\",\"doc\":\"user uploading the document\",\"type\":\"string\"}]}");
		/// <summary>
		/// version of the uploaded document
		/// </summary>
		private string _version;
		/// <summary>
		/// user uploading the document
		/// </summary>
		private string _user;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return MetaData._SCHEMA;
			}
		}
		/// <summary>
		/// version of the uploaded document
		/// </summary>
		public string version
		{
			get
			{
				return this._version;
			}
			set
			{
				this._version = value;
			}
		}
		/// <summary>
		/// user uploading the document
		/// </summary>
		public string user
		{
			get
			{
				return this._user;
			}
			set
			{
				this._user = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.version;
			case 1: return this.user;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.version = (System.String)fieldValue; break;
			case 1: this.user = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
